name: CI

on:
  push:
    branches: [master]
    paths:
      - "src/**"
  pull_request:
    branches: [master]
    paths:
      - "src/**"
  workflow_call:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Setup Python and uv for moto
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run linting
        run: bun run lint
      - name: Create Azurite config directory
        run: mkdir -p ./AzuriteConfig
      - name: Run tests
        run: bun run test
        timeout-minutes: 10
        env:
          NODE_ENV: test
